services:
  apisix:
    image: apache/apisix:${APISIX_IMAGE_TAG:-3.10.0-debian}
    restart: always
    volumes:
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ports:
      - "9180:9180"
      - "9080:9080"
      - "9091:9091"
      - "9443:9443"
      - "9092:9092"
    networks:
      - apisix

  etcd:
    image: bitnami/etcd:3.5.11
    restart: always
    volumes:
      - etcd_data:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379"
    networks:
      - apisix

  web1:
    image: nginx:1.19.0-alpine
    restart: always
    volumes:
      - ./upstream/web1.conf:/etc/nginx/nginx.conf
    ports:
      - "9081:80"
    environment:
      - NGINX_PORT=80
    networks:
      - apisix

  web2:
    image: nginx:1.19.0-alpine
    restart: always
    volumes:
      - ./upstream/web2.conf:/etc/nginx/nginx.conf
    ports:
      - "9082:80"
    environment:
      - NGINX_PORT=80
    networks:
      - apisix

  prometheus:
    image: prom/prometheus:v2.25.0
    restart: always
    volumes:
      - ./prometheus_conf/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - apisix

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_conf/provisioning:/etc/grafana/provisioning
      - ./grafana_conf/dashboards:/var/lib/grafana/dashboards
      - ./grafana_conf/config/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - apisix

  apisix-dashboard:
    image: apache/apisix-dashboard:latest
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./apisix-dashboard/api/conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    depends_on:
      - etcd
    networks:
      - apisix

networks:
  apisix:
    driver: bridge

volumes:
  etcd_data:
    driver: local
